# -*- coding: utf-8 -*-
"""Homework 1 Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8b-zWYx1UGB7-WSk6nDWm_uc-Wha_o_

**Task 1**

Given 2 variables that store strings of arbitrary length: phrase_1 and phrase_2.
Write code that checks which of these strings is longer.
"""

phrase_1 = 'Насколько проще было бы писать программы, если бы не заказчики'
phrase_2 = '640Кб должно хватить для любых задач. Билл Гейтс (по легенде)'

  if len(phrase_1) > len(phrase_2):
    print('Фраза 1 длиннее фразы 2')
  elif len(phrase_1) < len(phrase_2):
    print('Фраза 2 длиннее фразы 1')
  else:
    print('Фразы равной длины')

phrase_1 = '640Кб должно хватить для любых задач. Билл Гейтс (по легенде)'
phrase_2 = 'Насколько проще было бы писать программы, если бы не заказчики'
if len(phrase_1) > len(phrase_2):
  print('Фраза 1 длиннее фразы 2')
elif len(phrase_1) < len(phrase_2):
  print('Фраза 2 длиннее фразы 1')
else:
  print('Фразы равной длины')

phrase_1 = 'Насколько проще было бы писать программы, если бы не заказчики'
phrase_2 = 'Насколько проще было бы писать программы, если бы не заказчики'
if len(phrase_1) > len(phrase_2):
  print('Фраза 1 длиннее фразы 2')
elif len(phrase_1) < len(phrase_2):
  print('Фраза 2 длиннее фразы 1')
else:
  print('Фразы равной длины')

"""**Task 2**

Given a variable that stores a number (year). You need to write a program that will display whether a given year is a leap year or a common year.
"""

year= int(input())
if year%4 != 0:
    print('Обычный год')
elif year % 100 != 0:
    print('Високосный год')
elif year % 400 != 0:
    print('Обычный год')
else:
  print('Високосный год')

"""**Task 3**

write a program that will ask the user for the month and date of birth and display the corresponding zodiac sign.
"""

birth_day = int(input('Введите день рождения '))
birth_month = input('Введите месяц рождения ')
print('Ваш знак зодиака:')
if birth_day >= 20 and birth_day <= 31 and birth_month == 'Январь':
  print ('Водолей')
elif birth_day >= 1 and birth_day <= 18 and birth_month == 'Февраль':
  print ('Водолей')
elif birth_day >= 19 and  birth_day <= 29 and birth_month == 'Февраль':
  print ('Рыбы')
elif birth_day >= 1 and birth_day <= 20 and birth_month == 'Март':
  print ('Рыбы')
elif birth_day >= 20 and birth_day <= 31 and birth_month == 'Март':
  print ('Овен')
elif birth_day >= 1 and birth_day <= 19 and birth_month == 'Апрель':
  print ('Овен')
elif birth_day >= 20 and birth_day <= 30 and birth_month == 'Апрель':
  print ('Телец')
elif birth_day >= 1 and birth_day <= 20 and birth_month == 'Май':
  print ('Телец')
elif birth_day >= 21 and birth_day <= 31 and birth_month == 'Май':
  print ('Близнецы')
elif birth_day >= 1 and birth_day <= 21 and birth_month == 'Июнь':
  print ('Близнецы')
elif birth_day >= 22 and birth_day <= 30 and birth_month == 'Июнь':
  print ('Рак')
elif birth_day >= 1 and birth_day <= 22 and birth_month == 'Июль':
  print ('Рак')
elif birth_day >= 23 and birth_day <= 31 and birth_month == 'Июль':
  print ('Лев')
elif birth_day >= 1 and birth_day <= 22 and birth_month == 'Август':
  print ('Лев')
elif birth_day >= 23 and birth_day <= 31 and birth_month == 'Август':
  print ('Дева')
elif birth_day >= 1 and birth_day <= 22 and birth_month == 'Сентябрь':
  print ('Дева')
elif birth_day >= 23 and birth_day <= 30 and birth_month == 'Сентябрь':
  print ('Весы')
elif birth_day >= 1 and birth_day <= 22 and birth_month == 'Октябрь':
  print ('Весы')
elif birth_day >= 23 and birth_day <= 31 and birth_month == 'Октябрь':
  print ('Скорпион')
elif birth_day >= 1 and birth_day <= 22 and birth_month == 'Ноябрь':
  print ('Скорпион')
elif birth_day >= 23 and birth_day <= 30 and birth_month == 'Ноябрь':
  print ('Стрелец')
elif birth_day >= 1 and birth_day <= 21 and birth_month == 'Декабрь':
  print ('Стрелец')
elif birth_day >= 22 and birth_day <= 31 and birth_month == 'Декабрь':
  print ('Козерог')
elif birth_day >= 1 and birth_day <= 19 and birth_month == 'Январь':
  print ('Козерог')
else:
  print('Неверно введены данные')

"""«Водолей» (20.1–18.2), «Рыбы» (19.2–20.3), «Овен» (21.3–19.4), «Телец» (20.4–20.5), 
«Близнецы» (21.5–21.6), «Рак» (22.6–22.7), «Лев» (23.7–22.8), «Дева» (23.8–22.9), «Весы» (23.9–22.10), 
«Скорпион» (23.10–22.11), «Стрелец» (23.11–21.12), «Козерог» (22.12–19.1)

**Task 4**

Write a program for the selection of packages according to the size of the goods. Dimensions (width, length, height) are stored in variables (in centimeters):

Use the following rules:

if each of the three dimensions is less than or equal to 15 centimeters, then display "Box #1";
if at least one of the dimensions is greater than 15 centimeters but less than 50 centimeters, then print "Box #2";
if the product length is more than 2 meters, then print "Ski package";
in all other cases print "Standard box #3".
"""

width = int(input('Введите ширину товара '))
length = int(input('Введите длину товара '))
height = int(input('Введите высоту товара '))
print('Ваш необходима:')
if width <= 15 and length <= 15 and height <= 15:
  print ('Коробка №1')
elif width < 50 and length < 50 and height < 50:
  print ('Коробка №2')
elif length > 200:
  print ('Упаковка для лыж')
else:
  print ('Стандартная коробка №3')

"""**Task 5 (optional)**

Given a variable that stores a six-digit number (ticket number). Write a program that will determine if a given ticket is "lucky". A ticket is considered lucky if the sum of the first three digits matches the sum of the last three digits of the number.
"""

number = [int(i) for i in input()]
if len(number) == 6 and sum(number[:3]) == sum(number[3:]):
      print('Cчастливый билет')
elif len(number) == 6 and sum(number[:3]) != sum(number[3:]):
      print('Несчастливый билет')
else:
 print ('Введите шестизначный номер')

"""**Task 6 (optional)**

Write a program that can calculate the area of ​​three shapes (a circle, a triangle, and a rectangle). Request the type of the figure through user input, after which make a request for the characteristics of the figure:

1)if the user has selected a circle, request its radius,                        
2)if a triangle, the lengths of its three sides;         
3)if a rectangle, the lengths of its two sides.
"""

import math

figure = str(input('Введите наименование фигуры (круг/прямоугольник/треугольник)'))
if figure == 'круг':
  r = int(input('Ввдите радиус круга'))
  print(f"площадь фигуры = {(r ** 2) * math.pi: .2f} ")
elif figure == 'прямоугольник':
  a = int(input('Ввдите длину прямоугольника'))
  b = int(input('Ввдите ширину прямоугольника'))
  print(f"площадь фигуры = {a * b} ")
elif figure == 'треугольник':
  a = int(input('Ввдите сторону А треугольника'))
  b = int(input('Ввдите сторону В треугольника'))
  c = int(input('Ввдите сторону С треугольника'))
  p = (a + b + c)/2
  print(f"площадь фигуры = {(p * (p - a) * (p - b) * (p - c)) ** 0.5} ")
else:
  print('Введите правильное наименование фигуры, как указано в примере')